name: catprep
dependencies:
- execnet=1.3.0=py35_1
- mkl=11.3.3=0
- numpy=1.11.1=py35_0
- openssl=1.0.2h=1
- pandas=0.18.1=np111py35_0
- pep8=1.7.0=py35_0
- pip=8.1.2=py35_0
- py=1.4.31=py35_0
- pytest=2.9.2=py35_0
- pytest-cache=1.0=py35_0
- pytest-pep8=1.0.6=py35_0
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- pytz=2016.6.1=py35_0
- readline=6.2=2
- setuptools=23.0.0=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - args==0.1.0
  - clint==0.5.1
  - pkginfo==1.3.2
  - requests==2.10.0
  - requests-toolbelt==0.6.2
  - twine==1.7.4

